/** Structured, shadow-only causal evidence. No private reasoning traces or routing decisions. */
import type { Horizon } from "./shadow-learning.js";
import type { EvidenceState, SourceEvidence } from "./quantitative.js";
export type Attribution="CONFIRMED_DRIVER"|"LIKELY_DRIVER"|"POSSIBLE_DRIVER"|"MULTIPLE_COMPETING_DRIVERS"|"INSUFFICIENT_EVIDENCE"|"DRIVER_UNKNOWN";
export type ChannelState="SUPPORTED"|"WEAKLY_SUPPORTED"|"CONTRADICTED"|"UNCONFIRMED"|"INSUFFICIENT_EVIDENCE"|"DECAYING"|"INVALIDATED";
export type CausalChannel={id:string; from:string; to:string; order:"FIRST_ORDER_EFFECT"|"SECOND_ORDER_EFFECT"; horizon:Horizon; state:ChannelState; implication?:"UP"|"DOWN"; support:string[]; contradictions:string[]; sourceClass?:string; quantReference?:string; sampleSize?:number; sourceReputation?:string; updatedAt:string};
export type CausalGraph={storyId:string; createdAt:string; updatedAt:string; attribution:Attribution; channels:CausalChannel[]; corrections:Array<{original:string; correction:string; at:string; attribution:Attribution}>; conflicts:string[]; narrative:{known:string[]; changed:string; uncertain:string[]; active:string[]; contradicted:string[]; horizons:Horizon[]; latest:string; limitations:string[]}};
export type Case={side:"BULL_CASE"|"BEAR_CASE"; strongest:string[]; weakest:string[]; contradictions:string[]; channels:string[]; horizons:Horizon[]; state:Attribution};
export type Synthesis={bull:Case;bear:Case;attribution:Attribution;note:string};
export type AbnormalInvestigation={timestamp:string; xauMove:number; candidates:CausalChannel[]; attribution:Attribution; missing:string[]};
export function channel(id:string,from:string,to:string,order:CausalChannel["order"],horizon:Horizon,updatedAt:string, support:string[]=[], contradictions:string[]=[]):CausalChannel{return{id,from,to,order,horizon,state:support.length?contradictions.length?"WEAKLY_SUPPORTED":"SUPPORTED":"INSUFFICIENT_EVIDENCE",support,contradictions,updatedAt};}
export function synthesize(channels:CausalChannel[]):Synthesis{const supported=channels.filter(c=>c.state==="SUPPORTED"||c.state==="WEAKLY_SUPPORTED"), contradicted=channels.filter(c=>c.state==="CONTRADICTED"||c.contradictions.length); const bull:Case={side:"BULL_CASE",strongest:supported.filter(c=>c.implication==="UP").flatMap(c=>c.support),weakest:[],contradictions:contradicted.flatMap(c=>c.contradictions),channels:supported.filter(c=>c.implication==="UP").map(c=>c.id),horizons:[...new Set(supported.filter(c=>c.implication==="UP").map(c=>c.horizon))],state:"INSUFFICIENT_EVIDENCE"};const bear:Case={side:"BEAR_CASE",strongest:supported.filter(c=>c.implication==="DOWN").flatMap(c=>c.support),weakest:[],contradictions:contradicted.flatMap(c=>c.contradictions),channels:supported.filter(c=>c.implication==="DOWN").map(c=>c.id),horizons:[...new Set(supported.filter(c=>c.implication==="DOWN").map(c=>c.horizon))],state:"INSUFFICIENT_EVIDENCE"}; const attribution=!supported.length?"DRIVER_UNKNOWN":bull.channels.length&&bear.channels.length?"MULTIPLE_COMPETING_DRIVERS":supported.length>1&&contradicted.length===0?"LIKELY_DRIVER":"POSSIBLE_DRIVER";bull.state=bull.channels.length?attribution:"INSUFFICIENT_EVIDENCE";bear.state=bear.channels.length?attribution:"INSUFFICIENT_EVIDENCE";return{bull,bear,attribution,note:attribution==="MULTIPLE_COMPETING_DRIVERS"?"Competing evidence retained; no forced verdict.":"Structured evidence, not a trading signal."};}
export function investigate(xauMove:number, candidates:CausalChannel[], timestamp:string, marketFresh:boolean):AbnormalInvestigation{const viable=marketFresh?candidates.filter(c=>c.state!=="INVALIDATED"):[];return{timestamp,xauMove,candidates:viable,attribution:!marketFresh||!viable.length?"DRIVER_UNKNOWN":synthesize(viable).attribution,missing:marketFresh?[]:["FRESH market data unavailable"]};}
export function contextPack(graph:CausalGraph, experience:string[]=[], quant:string[]=[], reputation?:SourceEvidence):Record<string,unknown>{return{changed:graph.narrative.changed,known:graph.narrative.known.slice(-3),uncertain:graph.narrative.uncertain.slice(-3),channels:graph.channels.map(c=>({id:c.id,state:c.state,horizon:c.horizon,support:c.support.slice(0,2),contradictions:c.contradictions.slice(0,2)})),attribution:graph.attribution,experience:experience.slice(-3),quant:quant.slice(-3),sourceReputation:reputation?{factual:reputation.factualReliability,usefulness:reputation.marketUsefulness,sampleSize:reputation.sampleSize,state:reputation.state}:undefined};}
export function relevance(graph:CausalGraph, now:string):ChannelState{const age=Date.parse(now)-Date.parse(graph.updatedAt);return graph.corrections.length?"INVALIDATED":age>7*864e5?"DECAYING":"SUPPORTED";}
