import type { NewsArticle } from "./types.js";

export type OutputCheck = { ok: true } | { ok: false; reason: string };

function plain(text: string): string {
  return text.replace(/<[^>]*>/g, " ").replace(/&(?:amp|lt|gt|quot|#\d+);/gi, " ").replace(/\s+/g, " ").trim();
}
function normalized(text: string): string {
  return plain(text).toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}
function copiesSource(message: string, article: NewsArticle): boolean {
  const output = normalized(message);
  for (const source of [article.title, article.summary]) {
    const words = normalized(source).split(" ").filter(Boolean);
    if (words.length < 8) continue;
    for (let start = 0; start <= words.length - 8; start++) {
      const phrase = words.slice(start, start + 8).join(" ");
      if (phrase.length >= 45 && output.includes(phrase)) return true;
    }
  }
  return false;
}

/** Last code-level NEWS gate: no model response or fallback bypasses this. */
export function validateNewsOutput(message: string, article: NewsArticle): OutputCheck {
  // The one-line "Potensi arah emas" footer is generated by code, not the model;
  // it is excluded from the prose length and language checks.
  const blocks = message.trim().replace(/\n(?:<[^>]+>)?Potensi arah emas:[^\n]*$/, "").split(/\n\s*\n/).map((block) => plain(block));
  if (blocks.length !== 3 || !blocks[0].startsWith("⚠️ ")) return { ok: false, reason: "NEWS must have title, new fact and gold impact in three blocks" };
  const visible = blocks.join(" ");
  const wordCount = visible.split(/\s+/).filter(Boolean).length;
  if (wordCount < 35 || wordCount > 190 || message.length > 1500) return { ok: false, reason: `NEWS length ${wordCount} words outside safe range` };
  if (/\b(importance|urgency|new_information|source scoring|reasoning internal|score\s*\d+\s*\/\s*100|level dampak|bias dampak)\b/i.test(visible)) {
    return { ok: false, reason: "Internal metadata leaked into NEWS" };
  }
  // The Market Brain's internal action (BUY/SELL/WAIT/NO_TRADE) must never reach the groups.
  if (/\b(?:BUY|SELL|NO[_ -]TRADE)\b|keputusan internal|keputusanInternal/.test(visible)) return { ok: false, reason: "Internal brain action leaked into NEWS" };
  if (/https?:\/\/|www\.|\b(?:Reuters|Bloomberg|Politico|Truth Social)\s*[:—-]/i.test(visible)) return { ok: false, reason: "Raw source attribution or link in NEWS" };
  if (copiesSource(message, article)) return { ok: false, reason: "NEWS copies source text" };
  const idWords = visible.match(/\b(gw|lo|kita|gak|gk|klo|udah|belom|blm|yg|tp|jg|lg|bs|abis|bakal|doang|malah|makanya|intinya|kayak|emang|jadi|apa|baru|terjadi|trump|mengatakan|terbuka|bertemu|pertemuan|dengan|ini|karena|jalur|diplomasi|buat|emas|risiko|perang|bisa|kalau|hanya|tanpa|belum|jelas|dampak|pasar|suku|bunga|harga|naik|turun|tekanan|menjadi|akan|sementara|tetap|sehingga|terhadap|dari|pada|yang|dan|di|ke|untuk|sebagai|masih|lebih|dapat|sedang|setelah|sebelum|jika|namun|tetapi)\b/gi) ?? [];
  // Trader words the owner really uses (market, buyer, yield, safe haven...) are not
  // counted as English; the check only catches pasted English sentences.
  const enWords = visible.match(/\b(the|and|said|says|will|would|could|has|have|after|before|against|between|according|announced|announces|meeting|president|government|shipping|threat|attack|policy)\b/gi) ?? [];
  if (idWords.length < 8 || idWords.length <= enWords.length * 2) return { ok: false, reason: "NEWS is not predominantly Indonesian" };
  if (!/\b(emas|xau|gold)\b/i.test(blocks[2])) return { ok: false, reason: "Gold impact paragraph missing" };
  // Every alert must reason cause → effect, not just state a direction.
  if (!/→|->|\b(karena|jadi|makanya|bikin|bikinnya|sehingga|akibat\w*|dampak\w*|efek\w*|imbas\w*|artinya|alhasil|otomatis|gara-gara|lantaran|kalau|klo|jika|selama|begitu|lewat|melalui|via|sebab|tekan\w*|menekan|nekan|dorong\w*|mendorong|nopang|menopang|topang\w*|angkat|ngangkat|mengangkat|bebani|membebani|beban|picu|memicu|ganjal|mengganjal|jalur\w*|bergantung|tergantung|saluran|rantai)\b/i.test(blocks[2])) return { ok: false, reason: "Gold impact lacks cause-effect reasoning" };
  return { ok: true };
}


/** How timid an alert reads: hedge phrases in the fact + gold blocks, and whether the gold block takes a side at all. */
export function hedgeScore(message: string): { hedges: number; takesSide: boolean; timid: boolean } {
  const blocks = message.trim().split(/\n\s*\n/).map((b) => plain(b));
  const body = blocks.slice(1).join(" ").toLowerCase();
  const gold = (blocks[2] ?? "").toLowerCase();
  const hedges = (body.match(/berpotensi|bisa jadi|mungkin|belum jelas|perlu dipantau|patut dicermati|tergantung|bergantung|dua arah|belum tentu|masih dilihat|sulit ditebak|belum pasti|bisa saja|tidak menutup kemungkinan|belum otomatis|ketarik dua|dua arus|tabrakan/g) ?? []).length;
  // Opening the gold paragraph with "direction unclear" is timid by definition.
  const firstSentence = gold.split(/(?<=[.!?])\s/)[0] ?? "";
  const timidOpening = /belum jelas|dua arah|ketarik dua|dua arus|tabrakan|belum otomatis|belum pasti|campuran/.test(firstSentence);
  const takesSide = /ketekan|tertekan|nekan|menekan|kebantu|terbantu|nopang|menopang|ketahan|tertahan|condong|bearish|bullish|naik|turun|menguat|melemah|susah napas|dapet angin|kebawa/.test(gold);
  return { hedges, takesSide, timid: timidOpening || hedges >= 3 || (!takesSide && hedges >= 1) };
}

/**
 * Chat shorthand is hard to read for members: expand it to full words while keeping
 * the casual gw/lo tone. Applied by code to every group message, so it always holds.
 */
const SHORT: Array<[RegExp, string]> = [
  [/\byg\b/gi, "yang"], [/\btp\b/gi, "tapi"], [/\bjg\b/gi, "juga"], [/\bbs\b/gi, "bisa"], [/\bklo\b/gi, "kalau"], [/\bkl\b/gi, "kalau"],
  [/\bgk\b/gi, "gak"], [/\bga\b/gi, "gak"], [/\bblm\b/gi, "belum"], [/\bbelom\b/gi, "belum"], [/\blg\b/gi, "lagi"], [/\budh\b/gi, "udah"],
  [/\bdgn\b/gi, "dengan"], [/\bkrn\b/gi, "karena"], [/\bsm\b/gi, "sama"], [/\bbgt\b/gi, "banget"], [/\btdk\b/gi, "tidak"], [/\butk\b/gi, "untuk"],
  [/\bdr\b/gi, "dari"], [/\bspt\b/gi, "seperti"], [/\bjd\b/gi, "jadi"], [/\bkmrn\b/gi, "kemarin"], [/\bkemaren\b/gi, "kemarin"], [/\bsdh\b/gi, "sudah"],
  [/\bmrk\b/gi, "mereka"], [/\bnyari\b/gi, "nyari"], [/\bbnyk\b/gi, "banyak"], [/\bsampe\b/gi, "sampai"], [/\bgara2\b/gi, "gara-gara"]
];
export function readable(text: string): string {
  let out = text;
  for (const [re, word] of SHORT) out = out.replace(re, (m) => m[0] === m[0].toUpperCase() && m[0] !== m[0].toLowerCase() ? word[0].toUpperCase() + word.slice(1) : word);
  return out;
}
